export const PATHS = {
  usersPath: "/login",
  listsPath: "/list",
  contributorsPath: "/:id_list/contributors",
  todoPath: "/:id_list/todo",
  refreshPath: "/refresh",
};

export const MESSAGES = {
  SUC_REG: "Successful register",
  SUC_PATCH: "Succesful patch",
  SUC_DEL: "Succesful delete",
  NOT_HEAD_AUTH: "Authorization header is missing",
  INVALID_REG_DATA: "Invalid register data",
  INVALID_PATCH_DATA: "Invalid patch data",
  INVALID_DELETE_DATA: "Invalid delete data",
  INVALID_LIST_DATA: "Invalid creation list data",
  INVALID_TODO_DATA: "Ivalid creation todo data",
  INV_PASS: "Invalid password",
  INV_CRED: "Invalid credentials",
  INV_USR: "Invalid user",
  INV_ID: "Invalid ID",
  INV_ACCTION: "Invalid acction",
  INV_LINK: "Invalid link generator data",
  INV_PERM: "Invalid permission",
  ERR_MDB: "MongoDB error",
  USR_NOT_FOUND: "User not found",
  LIST_NOT_FOUND: "List not found",
  TODO_NOT_FOUND: "Todo not found",
  USER_ANY_LIST: "The user has no lists",
  INS_ERR: "Insert error",
  EXIST_US: "Existent user",
  MOD_BD_ERROR: "Error in database at modify user",
  REG_BD_ERROR: "Error in database at register user",
  DEL_BD_ERROR: "Error in database at delete user",
  NOT_PERMITTED: "The user does not have permission for that list",
  RND_LINK_NOT_FOUND: "Random link not found",
  LINK_EXP: "Link expired",
  NOT_AUTH: "There is no authorization data",
  INV_TOK: "Invalid token",
};
